### ISSUE TITLE
slapd-config db list-all : no such object 

### ISSUE THREAD

**Issue by willouuu** [cepharum/slapd-config#4]
Hi @cepharum 
I would test your product, but no work for me

```
$ slapd-config db list-all
No such object (32)
```

Log 256 sldap : 

> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 fd=24 ACCEPT from PATH=/var/run/ldapi (PATH=/var/run/ldapi)
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 op=0 BIND dn="" method=163
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 op=0 BIND authcid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth"
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 op=0 BIND dn="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" mech=EXTERNAL sasl_ssf=0 ssf=71
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 op=0 RESULT tag=97 err=0 text=
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 op=1 SRCH base="cn=config" scope=2 deref=0 filter="(olcDatabase=*)"
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 op=1 SRCH attr=dn
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 op=2 UNBIND
> mars 25 14:30:16 ldaptest slapd[7591]: conn=1011 fd=24 closed

Thanks you in advance

**Comment by soletan** [comment]
@willouuu Haven't got any notification on this issue so I'm very sorry for not having responded before. Are you still interested in fixing this issue or have you moved on?

**Comment by willouuu** [comment]
Hello
I'm sorry, I do not remember what your product serves.
I do not know why I wanted to use it ^^
But we might see the problem when I come home from vacation if this can fix the problem
Cordially
